root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
args_bin = []
bin = "./build/server"
cmd = "go build -tags=dev -o ./build/server ."
delay = 100
exclude_dir = [".vscode", "build", "node_modules"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
enabled = true
app_port = 8081
proxy_port = 8080

[screen]
clear_on_rebuild = false
keep_scroll = true
